### ISSUE TITLE
Mention about triggering builds on tags on Azure

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/azure-pipelines-templates#11]
We should mention that:

```yaml
trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
```

is needed.
