### ISSUE TITLE
Add a parameter for setting posargs to give to tox

### ISSUE THREAD

**Issue by astrofrog** [OpenAstronomy/azure-pipelines-templates#2]
We need to be able to do:

```yaml
jobs:

- template: template@repo
  parameters:
    envs:
    - linux: pep8
      posargs: -n=4
    - macosx: py37-test
```
