### ISSUE TITLE
Allow installing from brew cask?

### ISSUE THREAD

**Issue by dstansby** [OpenAstronomy/azure-pipelines-templates#31]
Currently one can do
```
jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    libraries:
      brew:
        - gfortran
```

But in this example installing `gfortran` doesn't work, because it needs to install from `cask` (ie. `brew cask install gfortran`). It would be nice if there was an option to install packages using `brew cask`.
